id: P009567
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14655
  title: འཇམ་དཔལ་མཚན་བརྗོད་ཀྱི་ཊིཀ་རྒྱས་པ།
  author: ''
  volumes:
    fb14761db3734fd0bffcf8e7f020dfd3:
      image_group_id: I1KG15737
      title: ''
      volume_number: 1
      total_pages: 434
      base_file: v001.txt
