id: I63C776FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:30:49+00:00'
last_modified: '2022-06-08T11:56:48.215451+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14655
  title: འཇམ་དཔལ་མཚན་བརྗོད་ཀྱི་ཊིཀ་རྒྱས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EF5A:
      image_group_id: I1KG15737
      title: ''
      total_pages: 434
      order: 1
      base_file: EF5A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
